### ISSUE TITLE
Various Fixes to FOFC - [merged]

### ISSUE THREAD

**Issue by jmstone** [IAS-Astrophysics/athenak#474]
In GitLab by @pdmullen on Jun 14, 2022, 16:23

_Merges fofc_v4_fix -> fofc_v4_

Please note that this MR is into the `fofc_v4` branch, **not** `master`.

# Summary
This branch includes various fixes to the `fofc_v4` branch.  Foremost, this branch adopts the same first-order flux correction function calls (and permutations) when first-order fluxes are triggered by the `fc_mask` (i.e., inside and about rks=1).  

# Tests
This PR should hopefully trigger CI, thereby testing the Bondi regression problem (and others).  Otherwise, I checked the Kommissarov blast wave tests (both `bamb=0.1` and `bamb=1.0`) and have integrated MHD tori to t=1000 M, both with and without FOFC (see below)

![fofc_fix](https://my-gitlab-bucket.s3.amazonaws.com/797964396/b1db8489f3ef0a37f48a40f8fabda023ccec85d0ff6a479a9b6ae6ecb3bd75cc/fofc_fix.png)

# To-Do
- [x] I wanted to get in this MR before I left PSU, but I should really confirm that the MHD tori can successfully integrate to 10,000 M, as this is the "benchmark" I have used previously.  I will confirm this when the run finishes.
- [ ] I would expect that `ideal_mhd.hpp` only contains functions relevant to `ideal_mhd.cpp`, however, it contains routines for all C2P and P2C functions (i.e., Newtonian, SR, and GR).  I think we should consider renaming `ideal_mhd.cpp`.  
- [ ] Presently, even if `fc_mask` triggers first order fluxes at a given face, FOFC will still check that flux.  We should consolidate the "two" flux corrections.
